name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      # - Read vault secrets in rancher-eio/read-vault-secrets.
      #id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Parse target tag
      run: |
        TARGET=${{ github.ref_name }}
        echo "TAG=${TARGET#v}" >> $GITHUB_ENV
  
  update-upgrade-responder:
      needs: publish
      runs-on: ubuntu-latest
      #permissions:
        #contents: write
      steps:
        - uses: actions/checkout@v4
        - name: Checkout external-production repository
          uses: actions/checkout@v4
          with:
            #repository: rancher-eio/external-production
            repository: anarkis/external-production
            ref: main
            token: ${{ secrets.GH_PAT }}
            path: external-production
            sparse-checkout: |
              manifests/upgrade-responder/resources/ConfigMap/upgrade-responder.json
            sparse-checkout-cone-mode: false

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        #- name: Install dependencies
          #run: |
            #python -m pip install --upgrade pip
            #pip install json
        - name: Test with pytest
          run: |
            python -c '
            import json
            data = {"Versions": [{"Name": "v2.1.1", "ReleaseDate": "2022-05-13T01:31:29.99Z", "Tags": ["latest", "2.1.1"]}]}
            with open(".github/upgrade-responder.json", "w") as f: json.dump(data, f, indent=2)
            '
        - name: Commit and push changes to neuvector
          #env:
            #GITHUB_TOKEN: ${{ secrets.GH_PAT  }}
          run: |
            ls -la
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
            BRANCH_NAME="auto-update/upgrade-responder-$(date +%Y%m%d%H%M%S)"
            echo "Creating and pushing branch: $BRANCH_NAME"

            git checkout -b "$BRANCH_NAME"
            git add .github/upgrade-responder.json
            git commit -m "Automated commit by GitHub Actions"
            git push origin "$BRANCH_NAME"
            gh pr create --base main --head "$BRANCH_NAME" --title "Automated: Update upgrade-responder.json" --body "This PR updates the \`upgrade-responder.json\` file with the latest version information, generated automatically by GitHub Actions."

        #- name: Commit and push changes to external-production
          #env:
            #GITHUB_TOKEN: ${{ secrets.GH_PAT  }}
          #run: |
            #cd external-production/
            #git checkout -b "$BRANCH_NAME"
            #git add upgrade-responder.json
            #git remote -v
            #git status
            #git commit -m "Automated commit by GitHub Actions"            
            #git push origin "$BRANCH_NAME"
            #gh pr create --base main --head "$BRANCH_NAME" --title "Automated: Update upgrade-responder.json" --body "This PR updates the \`upgrade-responder.json\` file with the latest version information, generated automatically by GitHub Actions."

        #check
        #if not sucess (EXTERNAL) create automated issue for EIO priority 1

        